# Generated by Django 5.2 on 2025-04-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
